"""
Report Generation Router — templated report generation via multi-agent pipeline.
"""

import json
import logging
import time

from fastapi import APIRouter
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from imi_report_templates import get_template, list_templates, TEMPLATES
from imi_agents import _call_ollama
from imi_rag import query as rag_query

logger = logging.getLogger("imi_reports")

router = APIRouter(prefix="/klaus/imi", tags=["imi-reports"])


class ReportRequest(BaseModel):
    template_type: str
    query: str = ""
    brand: str = ""


@router.get("/report-templates")
async def report_templates():
    """List available report templates."""
    return JSONResponse({"templates": list_templates()})


@router.post("/report/generate")
async def generate_report(req: ReportRequest):
    """Generate a full report using a template + RAG + pipeline."""
    template = get_template(req.template_type)
    if not template:
        return JSONResponse(
            {"error": f"Unknown template: {req.template_type}", "available": [t["type"] for t in list_templates()]},
            status_code=400
        )

    start = time.time()

    # Build search query from template + user input
    search_query = template["rag_query"]
    if req.query:
        search_query = f"{req.query} {search_query}"
    if req.brand:
        search_query = f"{req.brand} {search_query}"

    # Retrieve relevant data via RAG
    chunks = rag_query(search_query, n=20)

    # Format data context
    data_context = ""
    if chunks:
        by_dataset = {}
        for c in chunks:
            ds = c["dataset"]
            if ds not in by_dataset:
                by_dataset[ds] = []
            by_dataset[ds].append(c["text"])

        lines = []
        for ds, texts in by_dataset.items():
            lines.append(f"=== {ds} ===")
            for t in texts:
                lines.append(f"  {t}")
            lines.append("")
        data_context = "\n".join(lines)

    # Generate each section
    sections = []
    brand_context = f" for {req.brand}" if req.brand else ""
    query_context = f" Focus on: {req.query}" if req.query else ""

    for section in template["sections"]:
        system = f"""You are Klaus, the AI insight engine of IMI International — a 54-year-old global marketing research firm (founded 1971, Toronto, 45+ countries, 50,000+ case studies).

You are writing the "{section['title']}" section of a {template['name']}{brand_context}.{query_context}

IMI FRAMEWORKS TO APPLY:
- Say/Do Gap: stated intentions vs actual behavior
- 12 Growth Levers: Brand, Wellness, Delivery, Digital, Emotion, Promotion, Influence, In-Store, Experience, Recommendation, Social Media, Traditional
- Brand Health Funnel: awareness → familiarity → consideration → purchase → recommendation

RULES:
- ONLY use numbers from the provided data. NEVER fabricate.
- Bold all key numbers: **47%**, **+8 NPS points**
- Cite the dataset name for every number
- Be direct and authoritative — no hedging

DATA:
{data_context}"""

        content = _call_ollama(system, section["prompt"], temperature=0.3, max_tokens=1024)
        sections.append({
            "title": section["title"],
            "content": content
        })

    # Combine into full report
    report_md = f"# {template['name']}{brand_context}\n\n"
    if req.query:
        report_md += f"*Focus: {req.query}*\n\n"
    report_md += f"*Generated by Klaus AI — IMI International*\n\n---\n\n"

    for s in sections:
        report_md += f"## {s['title']}\n\n{s['content']}\n\n---\n\n"

    elapsed_ms = (time.time() - start) * 1000

    return JSONResponse({
        "report": report_md,
        "template": req.template_type,
        "sections": len(sections),
        "datasets_used": list({c["dataset"] for c in chunks}) if chunks else [],
        "rag_chunks": len(chunks),
        "processing_time_ms": round(elapsed_ms, 1)
    })
